student.height=c(50,60,70)
is.logical(student.height)
is.numeric(student.height)
as.logical(student.height)
as.numeric(student.height)
as.character(student.height)
my_seq=c(1:10)
print(my_seq)
new_seq=c(seq(1,50,b=3))
new_seq
e=c(5,4,6,0)
e
class(e)
as.logical(e)
as.character(e)
as.numeric(e)
x=c(12,8,9,6)
mean(x)
median(x)
mode(x)
my_seq=c(1:100)
my_seq
new_seq=c(seq(1,100,by=5))
new_seq